### ISSUE TITLE
[DEV] Implement CSV downloads for collections

### ISSUE THREAD

**Issue by jesicarson** [participedia/api#1006] opened 2020-11-18 22:21 UTC
On collections landing pages, add download csv button on the cases/methods/orgs tabs, allowing downloading the full collection as separate csvs for each type. Exactly the same as how we deal with downloading results on the search page. 

![Screen Shot 2020-11-18 at 2 22 33 PM](https://user-images.githubusercontent.com/130878/99595477-a33fa080-29a9-11eb-84c6-7ae59bd94d1c.png)

**Comment by paninee** [comment] 2020-11-27 18:05
Merged into `master`

**Comment by ascott** [comment] 2020-12-01 20:43
this is on staging now, looks like there is bug where the csv does not include any records. also introduced a regression on the main search csv download

**Comment by paninee** [comment] 2020-12-13 19:30
Live and the CSV includes correct records now.

**Closed by paninee** 2020-12-13 19:30 UTC
Labels: P1

**Comment by plscully** [comment] 2020-12-13 19:36
> @paninee  -- Awesome! Thank you!
> > Live and the CSV includes correct records now.
