### ISSUE TITLE
Strange error on PUT 

### ISSUE THREAD

**Issue by davidascher** [participedia/api#130] opened 2017-06-10 23:49 UTC
```
error: Exception in PUT /case/953 => error: column "authors" of relation "cases" does not exist
PUT /case/953 500 24.688 ms - 171
```

Haven't dug into what's happening.  It happens when saving an edited case, sometimes.

**Comment by dethe** [comment] 2017-06-11 02:10
Hmm, it definitely has such a column. I'll see if I can reproduce and fix.

**Comment by dethe** [comment] 2017-06-13 07:07
When frontend sent a change it didn't send authors, but it got back an authors with an extra entry (because sending a change increments authors by one) and sends authors on the subsequent call. The edit API wasn't filtering out authors (which is a generated field, api-side) and tried to save it, which broke, but not on the first edit call. 

Fixed in PR #134

**Closed by dethe** 2017-06-13 07:07 UTC
